# Generated by Django 4.0.3 on 2022-04-08 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_pessoa_alter_receita_data_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 4, 8, 18, 3, 26, 292181)),
        ),
    ]
