# Generated by Django 4.0.3 on 2022-04-11 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_receita_publicada_alter_receita_data_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 4, 11, 10, 28, 49, 35437)),
        ),
        migrations.AlterField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
