# Generated by Django 4.0.3 on 2022-04-11 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_alter_receita_data_receita_alter_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2022, 4, 11, 10, 37, 33, 264065)),
        ),
    ]
