# Generated by Django 4.0.3 on 2022-04-25 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0010_alter_receita_data_receita_alter_receita_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 9, 57, 48, 976530)),
        ),
    ]
